default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:
  password:

development:
  <<: *default
  database: power_cut

test:
  <<: *default
  database: power_cut_test

production:
  <<: *default
